version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3bkr@2251998
    ports:
      - "5433:5432"  # Expose the PostgreSQL port to the host  
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist the PostgreSQL data
  web:
    build: .
    env_file:
      - ./app/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata:
